/* ARC main-page completion actions v33 */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const app=window.ARCApp;
  if(!app?.engine)return;

  const engine=app.engine;
  const originalComplete=engine.onComplete;
  let pending=null;
  let handled=false;

  function ensurePanel(){
    let panel=$('completionActions');
    if(panel)return panel;
    const runCard=document.querySelector('.run-card');
    if(!runCard)return null;
    panel=document.createElement('div');
    panel.id='completionActions';
    panel.className='end-panel';
    panel.hidden=true;
    panel.innerHTML=`
      <div class="section-title-row"><h3>SAVE COMPLETED TEST</h3><span class="pill accent">COMPLETE</span></div>
      <p class="muted">Choose where this completed test should go.</p>
      <div class="field"><label>Email Recipient (optional)</label><input id="completionEmail" type="email" placeholder="name@example.com"></div>
      <div class="row">
        <button id="saveCompletedLocal" class="good">SAVE LOCALLY</button>
        <button id="emailCompletedTest" class="secondary">EMAIL TEST</button>
        <button id="saveAndEmailCompleted" class="primary">SAVE LOCALLY + EMAIL</button>
      </div>
      <div id="completionActionStatus" class="status info">Complete the test to enable save options.</div>`;
    const runList=$('runList');
    if(runList)runCard.insertBefore(panel,runList);
    else runCard.appendChild(panel);
    return panel;
  }

  function setStatus(text,kind='info'){
    const el=$('completionActionStatus');
    if(!el)return;
    el.className=`status ${kind}`;
    el.textContent=text;
  }

  function showPanel(){
    const panel=ensurePanel();
    if(panel){
      panel.hidden=false;
      setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'center'}),50);
    }
    const rs=$('runStatus');
    if(rs){
      rs.className='status good';
      rs.textContent='TEST COMPLETE — choose how to save or send this test.';
    }
    setStatus('Choose SAVE LOCALLY, EMAIL TEST, or SAVE LOCALLY + EMAIL.','info');
  }

  function hidePanel(){
    const panel=$('completionActions');
    if(panel)panel.hidden=true;
  }

  function latestCompletedForRun(runId){
    try{return window.NEXUSTiltStore?.listCompletedTests?.().find(x=>x.runId===runId)||null}catch{return null}
  }

  function emailSubject(s){
    const p=s?.plan||{};
    return `ARC TILT Test — ${p.equipmentId||p.equipmentName||'Equipment'} — ${p.projectName||'Project'}`;
  }

  function emailBody(s){
    const p=s?.plan||{}, end=s?.testEnd||{}, records=s?.records||[];
    const rows=records.map((r,i)=>`${i+1}. ${r.testPoint||r.testId||'Test Point'}: ${r.reading||'—'}`).join('\n');
    return [
      'ARC Systems Completed TILT Test','',
      `Project: ${p.projectName||''}`,
      `Equipment ID: ${p.equipmentId||p.equipmentName||''}`,
      `Equipment Type: ${p.equipmentType||''}`,
      `Tester: ${$('technicianName')?.value.trim()||end.endedBy||''}`,
      `Started: ${s?.startedAt?new Date(s.startedAt).toLocaleString():''}`,
      `Completed: ${s?.completedAt?new Date(s.completedAt).toLocaleString():new Date().toLocaleString()}`,
      `Status: ${end.endedByTester?'ENDED':'COMPLETED'}`,'',
      'Accepted Readings:',rows||'No accepted readings recorded.','',
      'Generated by ARC Systems'
    ].join('\n');
  }

  function openEmail(s){
    const to=$('completionEmail')?.value.trim()||'';
    const href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(emailSubject(s))}&body=${encodeURIComponent(emailBody(s))}`;
    window.location.href=href;
  }

  async function saveLocal(){
    if(!pending)throw new Error('No completed ARC test is waiting to be saved.');
    const existing=latestCompletedForRun(pending.runId);
    if(existing)return existing;
    await originalComplete(pending);
    const saved=latestCompletedForRun(pending.runId);
    if(!saved)throw new Error('ARC could not verify the completed test in local storage.');
    return saved;
  }

  async function finishEmailOnly(){
    if(!pending)return;
    try{await window.NEXUSTiltDB?.removeRun?.(pending.runId)}catch(e){console.error(e)}
    window.dispatchEvent(new Event('arc-records-changed'));
  }

  ensurePanel();

  engine.onComplete=(s)=>{
    pending=structuredClone(s);
    handled=false;
    showPanel();
    return s;
  };

  $('saveCompletedLocal')?.addEventListener('click',async()=>{
    if(handled)return;
    try{
      setStatus('Saving completed test locally...','info');
      await saveLocal();
      handled=true;
      setStatus('TEST SAVED LOCALLY — available under Completed Test Records.','good');
      const rs=$('runStatus');if(rs)rs.textContent='TEST COMPLETE — SAVED LOCALLY.';
      window.dispatchEvent(new Event('arc-records-changed'));
    }catch(e){setStatus(`SAVE ERROR: ${e?.message||e}`,'bad')}
  });

  $('emailCompletedTest')?.addEventListener('click',async()=>{
    if(handled)return;
    if(!pending)return setStatus('No completed test is waiting to be emailed.','bad');
    try{
      const snapshot=structuredClone(pending);
      await finishEmailOnly();
      handled=true;
      setStatus('Opening your email app with the completed test.','good');
      const rs=$('runStatus');if(rs)rs.textContent='TEST COMPLETE — EMAIL PREPARED.';
      openEmail(snapshot);
    }catch(e){setStatus(`EMAIL ERROR: ${e?.message||e}`,'bad')}
  });

  $('saveAndEmailCompleted')?.addEventListener('click',async()=>{
    if(handled)return;
    if(!pending)return setStatus('No completed test is waiting to be saved.','bad');
    try{
      const snapshot=structuredClone(pending);
      setStatus('Saving locally, then opening email...','info');
      await saveLocal();
      handled=true;
      window.dispatchEvent(new Event('arc-records-changed'));
      setStatus('TEST SAVED LOCALLY — opening your email app.','good');
      const rs=$('runStatus');if(rs)rs.textContent='TEST COMPLETE — SAVED LOCALLY + EMAIL PREPARED.';
      openEmail(snapshot);
    }catch(e){setStatus(`SAVE / EMAIL ERROR: ${e?.message||e}`,'bad')}
  });

  addEventListener('arc-resume-run',()=>{pending=null;handled=false;hidePanel()});
})();